# These are supported funding model platforms

# github: [user1, user2] # Replace with up to 4 GitHub Sponsors-enabled usernames
# patreon: user # Replace with a single Patreon username
# open_collective: project # Replace with a single Open Collective username
# ko_fi: user # Replace with a single Ko-fi username
# tidelift: npm/package-name # Replace with a single Tidelift platform-name/package-name
# community_bridge: project # Replace with a single Community Bridge project-name
# liberapay: user # Replace with a single Liberapay username
# issuehunt: user # Replace with a single IssueHunt username
# otechie: user # Replace with a single Otechie username
# lfx_crowdfunding: project # Replace with a single LFX Crowdfunding project-name
# custom: ['https://example.com'] # Replace with up to 4 custom sponsorship URLs
