name: Deploy School Management System

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '18.x'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.deploy.outputs.url }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        
    - name: Deploy Backend to Railway
      id: deploy
      uses: bervProject/railway-deploy@main
      env:
        RAILWAY_TOKEN: 2c291c17-9581-44f9-89a0-0da65976bead
      with:
        service: 8a40dbd6-f389-4f50-b53e-9689a4977c91
        detach: false
        
    - name: Wait for Backend
      run: sleep 30

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd frontend
        CI=false npm run build
      env:
        REACT_APP_API_URL: ${{ needs.deploy-backend.outputs.backend-url }}
        
    - name: Deploy Frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: Wcy6d56q7FEBKup6677RqcwP
        vercel-org-id: team_Z7lnGIIr1PEbM5kkmbLcwFcH
        vercel-project-id: prj_RLZw3QVlINTR6P6nrlUTdEh7y6fL
        working-directory: frontend
        vercel-args: '--prod'
        
    - name: Deployment Summary
      run: |
        echo "✅ Deployment Complete!"
        echo "Backend: Railway"
        echo "Frontend: Vercel"
        echo "Check your dashboards for deployment URLs"
