name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    - name: Check Backend Dependencies
      run: |
        cd backend
        npm outdated || true
        npm audit --audit-level info || true

    - name: Check Frontend Dependencies  
      run: |
        cd frontend
        npm outdated || true
        npm audit --audit-level info || true

    - name: Create Issue for Outdated Dependencies
      uses: actions/github-script@v7
      with:
        script: |
          const title = `Weekly Dependency Review - ${new Date().toISOString().split('T')[0]}`;
          const body = `## 📦 Weekly Dependency Review
          
          This is an automated weekly check of project dependencies.
          
          ### Actions Required:
          - [ ] Review backend dependencies
          - [ ] Review frontend dependencies  
          - [ ] Update critical security vulnerabilities
          - [ ] Test updated dependencies
          
          ### Commands to Check:
          \`\`\`bash
          # Backend
          cd backend && npm outdated && npm audit
          
          # Frontend
          cd frontend && npm outdated && npm audit
          \`\`\`
          
          ### Priority Updates:
          - Security vulnerabilities (HIGH)
          - Major version updates (MEDIUM)
          - Feature updates (LOW)
          `;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['dependencies', 'maintenance']
          });
