name: Frontend Deployment to Vercel

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '18.x'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Deploy Frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: Wcy6d56q7FEBKup6677RqcwP
        vercel-org-id: avishek-kumars-projects
        vercel-project-id: prj_RLZw3QVlINTR6P6nrlUTdEh7y6fL
        working-directory: ./frontend
        vercel-args: '--prod'
      env:
        REACT_APP_API_URL: https://sms-service.up.railway.app/api
        GENERATE_SOURCEMAP: false
